version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  docs-voting-api:
    image: tedim52/docs-voting-app:latest
    container_name: docs-voting-api
    ports:
      - "9111:9111"
    environment:
      - REDIS_HOST=redis://redis:6379
    depends_on:
      - redis
