apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: azure-vote-back
          image: bitnami/redis:6.0.8
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_PORT_NUMBER
              value: "6380"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 6380
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
    - port: 6380
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: azure-vote-front
          image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: "redis-proxy-overlay"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  labels:
    app: azure-vote-front
spec:
  type: ClusterIP
  selector:
    app: azure-vote-front
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-proxy-overlay
  labels:
    app: redis-proxy-overlay
spec:
  selector:
    matchLabels:
      app: redis-proxy-overlay
  template:
    metadata:
      labels:
        app: redis-proxy-overlay
    spec:
      containers:
      - name: proxy
        image: docker.io/kurtosistech/redis-proxy-overlay:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
        env:
          - name: REDIS_ADDR
            value: "azure-vote-back:6380"
          - name: PORT
            value: "6379"
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: proxy-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: proxy-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-proxy-overlay
  labels:
    app: redis-proxy-overlay
spec:
  type: ClusterIP
  selector:
    app: redis-proxy-overlay
  ports:
  - name: tcp-proxy
    port: 6379
    targetPort: 6379
