version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: kardinal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
