schema = 3

[mod]
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/go-logr/logr"]
    version = "v0.4.0"
    hash = "sha256-xeGTv0SMhCkLbIOH5Su2q/74B+OeOxsyEVYtQepF3/E="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.5"
    hash = "sha256-pyfTIu1fx6cGYHhm+yi8YP2TgERnnqKRjqSV7WGb1Yk="
  [mod."github.com/google/gofuzz"]
    version = "v1.1.0"
    hash = "sha256-PSNufXo20YXfSNbayCc3hdujKZT5EW4lybsQ+WJ0Imo="
  [mod."github.com/googleapis/gnostic"]
    version = "v0.5.5"
    hash = "sha256-KpSB2tHJsikuI86gZFCOod1MAbZEiiSrLCmVoAcm9X8="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.5"
    hash = "sha256-644gtN58Py6dYU8OAM10R95YuD2W4Aj3ZS+NuxOyb9c="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.11"
    hash = "sha256-/rcZZy458AsEqrSgtneGghVUpHNXJfT66QQHI6hyERU="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.1"
    hash = "sha256-5D1HGVBc/REwPVdlPYcXsbZM80OIh7V5uiyKAbMA5qo="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210520170846-37e1c6afe023"
    hash = "sha256-dwPXxrv+JephmrlF5fRdypRTd4ka/VFx7jbvJEzOXr0="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20200107190931-bf48bf16ab8d"
    hash = "sha256-r+VK6vgr8pMOmLXonG6YhBSUQ+kZJzdHgpV/YFZsOeo="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20210616094352-59db8d763f22"
    hash = "sha256-K1N3bTNNX8hv6g5y+b8hrgBEZUF78b+etCrvuBkp4xg="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210220032956-6a3ed077a48d"
    hash = "sha256-BQ9U/OJuxKwVGsfMff6reDsBTmBiDSGmMy5lgYdF0XY="
  [mod."golang.org/x/text"]
    version = "v0.3.6"
    hash = "sha256-yP/VW8PvNE6ub82oSu0mnG3VZXMo1PCSbwsWbciQDaw="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."google.golang.org/appengine"]
    version = "v1.6.5"
    hash = "sha256-cE9jZUiPSk7GMhhpdcl4NS6OkGqwh9IU3exKiqs+3ns="
  [mod."google.golang.org/protobuf"]
    version = "v1.26.0"
    hash = "sha256-RzsCfEkChrIx/LL3SoBlsTRQ3kKbysfhG4HOujdAdLw="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20210107192922-496545a6307b"
    hash = "sha256-j8yDji+vqsitpRZirpb4w/Em8nstgf28wpwkcrOlxBk="
  [mod."k8s.io/api"]
    version = "v0.22.2"
    hash = "sha256-DXAn/q5GE86vcO3KOHk30Ve9f6DDl5ooHWTG1kll3Yk="
  [mod."k8s.io/apimachinery"]
    version = "v0.22.2"
    hash = "sha256-TUg+uQWYw/k9GtBoFoparT9+GReG/zY1HvDgReAH/4w="
  [mod."k8s.io/client-go"]
    version = "v0.22.2"
    hash = "sha256-DAmH1NENDtLkxBsipHS5xEm8uagCkGrjoGr5tGGC8hk="
  [mod."k8s.io/klog/v2"]
    version = "v2.9.0"
    hash = "sha256-k8Zj7Ypn6UJRyprmWD3bvgoAXQI1CmPIjqugsdRBYFk="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20210819203725-bdf08cb9a70a"
    hash = "sha256-twbsCnkBI6tf0oRp2K7mfBAkom0QFUmynwnoa5ggFfk="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.1.2"
    hash = "sha256-3K0/Dl649UR/f067hi7kOoXdiTHJuWlMZKeNOvJFA2k="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.2.0"
    hash = "sha256-HHqIfaFuKGalif3bP2CcHm8MT8Ily1kJQL9Q8Kz2WHA="
