# Existing services and deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-prod
  template:
    metadata:
      labels:
        app: redis-prod
    spec:
      containers:
        - name: redis-prod
          image: bitnami/redis:6.0.8
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_PORT_NUMBER
              value: "6380"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 6380
              name: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-prod
spec:
  ports:
    - port: 6380
  selector:
    app: redis-prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
      version: v1
  template:
    metadata:
      labels:
        app: azure-vote-front
        version: v1
    spec:
      containers:
        - name: azure-vote-front
          image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: "redis-prod"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
      version: v2
  template:
    metadata:
      labels:
        app: azure-vote-front
        version: v2
    spec:
      containers:
        - name: azure-vote-front-v2
          image: mcr.microsoft.com/azuredocs/azure-vote-front:v2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: "redis-proxy-overlay"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: ClusterIP
  selector:
    app: azure-vote-front
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-proxy-overlay
  labels:
    app: redis-proxy-overlay
spec:
  selector:
    matchLabels:
      app: redis-proxy-overlay
  template:
    metadata:
      labels:
        app: redis-proxy-overlay
    spec:
      containers:
        - name: proxy
          image: docker.io/kurtosistech/redis-proxy-overlay:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_ADDR
              value: "redis-prod:6380"
            - name: PORT
              value: "6379"
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - mountPath: /data
              name: proxy-data
          resources:
            limits:
              memory: 256Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
      volumes:
        - name: proxy-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-proxy-overlay
  labels:
    app: redis-proxy-overlay
spec:
  type: ClusterIP
  selector:
    app: redis-proxy-overlay
  ports:
    - name: tcp-proxy
      port: 6379
      targetPort: 6379

# Adding Istio Gateway
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: azure-vote-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

# Adding Virtual Service for routing
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: azure-vote
spec:
  hosts:
    - "*"
  gateways:
    - azure-vote-gateway
  http:
    - route:
        - destination:
            host: azure-vote-front
            subset: v1
          weight: 100
      mirror:
        host: azure-vote-front
        subset: v2
      mirror_percent: 10
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: DestinationRule
# metadata:
#   name: azure-vote-destination
# spec:
#   host: azure-vote-front
#   subsets:
#     - name: v1
#       labels:
#         version: v1
#     - name: v2
#       labels:
#         version: v2
