// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package types

import (
	compose "github.com/compose-spec/compose-go/types"
)

// DevFlowSpec defines model for DevFlowSpec.
type DevFlowSpec struct {
	DockerCompose *[]compose.ServiceConfig `json:"docker-compose,omitempty"`
	ImageLocator  *string                  `json:"image-locator,omitempty"`
	ServiceName   *string                  `json:"service-name,omitempty"`
}

// ProdFlowSpec defines model for ProdFlowSpec.
type ProdFlowSpec struct {
	DockerCompose *[]compose.ServiceConfig `json:"docker-compose,omitempty"`
}

// Topology defines model for Topology.
type Topology struct {
	Graph *struct {
		Nodes *[]struct {
			Id             *string   `json:"id,omitempty"`
			ServiceName    *string   `json:"serviceName,omitempty"`
			ServiceVersion *string   `json:"serviceVersion,omitempty"`
			TalksTo        *[]string `json:"talks_to,omitempty"`
		} `json:"nodes,omitempty"`
	} `json:"graph,omitempty"`
}

// GetTopologyParams defines parameters for GetTopology.
type GetTopologyParams struct {
	// Namespace The namespace for which to retrieve the topology
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// PostDeployJSONRequestBody defines body for PostDeploy for application/json ContentType.
type PostDeployJSONRequestBody = ProdFlowSpec

// PostFlowCreateJSONRequestBody defines body for PostFlowCreate for application/json ContentType.
type PostFlowCreateJSONRequestBody = DevFlowSpec

// PostFlowDeleteJSONRequestBody defines body for PostFlowDelete for application/json ContentType.
type PostFlowDeleteJSONRequestBody = ProdFlowSpec
