schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.54.0"
    hash = "sha256-0GHaPyaZ6PtSrRPoVDs1zWxgo9kwSm/cxHCD0+Q6C8g="
  [mod."cloud.google.com/go/bigquery"]
    version = "v1.4.0"
    hash = "sha256-niyEg/99kFPoAnQ5CQHfS8GEfQYGKtNbD36nNuSF4zo="
  [mod."cloud.google.com/go/datastore"]
    version = "v1.1.0"
    hash = "sha256-wyOuic/vp33s1QiybElwERALQwPrn8gFHDAdlTBcv1Q="
  [mod."cloud.google.com/go/pubsub"]
    version = "v1.2.0"
    hash = "sha256-pVKDdQS2A1P0inU6mkI1aUrfIuHgL5ib8RpKt/rYQVI="
  [mod."cloud.google.com/go/storage"]
    version = "v1.6.0"
    hash = "sha256-pF2Ff0UVveFDI5yDX1G3MV4bCx++x+mTQ4OIHgPIGqA="
  [mod."dmitri.shuralyov.com/gpu/mtl"]
    version = "v0.0.0-20190408044501-666a987793e9"
    hash = "sha256-H+xcbVdCNDahWZPgwk4k+XxnM73g0hwaFY7x+OAATcc="
  [mod."github.com/Azure/go-autorest"]
    version = "v14.2.0+incompatible"
    hash = "sha256-dvWOcudtx0NP6U2RDt40hwtELFRdYdLEklRWYterRN0="
  [mod."github.com/Azure/go-autorest/autorest"]
    version = "v0.11.18"
    hash = "sha256-j6IViAvhZ5r06n1qpGVy4aUF/pEYhQknkTQJa1qFtBI="
  [mod."github.com/Azure/go-autorest/autorest/adal"]
    version = "v0.9.13"
    hash = "sha256-hPrY0ZmA/x6NDCViEdlg44nPjQirxA4ct5SzUMp43NY="
  [mod."github.com/Azure/go-autorest/autorest/date"]
    version = "v0.3.0"
    hash = "sha256-PWFHUZ9jMJ6gkMCnRpR89s/aI3YdtzskIePj8Ulu4dc="
  [mod."github.com/Azure/go-autorest/autorest/mocks"]
    version = "v0.4.1"
    hash = "sha256-ZzK6AL03DbclhBC8gF9bnQadnAn5hQSEXOlmglZMCEg="
  [mod."github.com/Azure/go-autorest/logger"]
    version = "v0.2.1"
    hash = "sha256-xGqpcF7fL1MQCN4xXTHpAFDzEA5f4p6kdb9yV1+uB4k="
  [mod."github.com/Azure/go-autorest/tracing"]
    version = "v0.6.0"
    hash = "sha256-CcLYoOyRcMo4aRRYN+TBbaHtJqDra4e0qo3cmGZIB74="
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/BurntSushi/xgb"]
    version = "v0.0.0-20160522181843-27f122750802"
    hash = "sha256-ck+gNOSXNYy/ji6mpSX3OTHgCDm2nww+3ZKu4lAXl6I="
  [mod."github.com/NYTimes/gziphandler"]
    version = "v0.0.0-20170623195520-56545f4a5d46"
    hash = "sha256-4mTVrxEH1Cu3MVhm/nB+Zm8b2oYS4SecOHjnbT5Pk7s="
  [mod."github.com/PuerkitoBio/purell"]
    version = "v1.1.1"
    hash = "sha256-Hjf8ZNNdwcRd50A9QNrcCj17gu/6f1iKzVTVrrMrojA="
  [mod."github.com/PuerkitoBio/urlesc"]
    version = "v0.0.0-20170810143723-de5bf2ad4578"
    hash = "sha256-nL0/0QM0Pec83vBlwXvQ8g5SvvZnCQgzD1apxfHNGlg="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20190424111038-f61b66f89f4a"
    hash = "sha256-pcrINvdGpQExaSQv1j19L0NLWcvZL8jXQMsvMlVq8ss="
  [mod."github.com/bsm/ginkgo/v2"]
    version = "v2.12.0"
    hash = "sha256-rZ9AF2RPWwQcgFmh3bmUXDaTLL14fQfPtv+DuC8xqzQ="
  [mod."github.com/bsm/gomega"]
    version = "v1.27.10"
    hash = "sha256-EltjBddI8lJOxiONk2GgbjtHp7ysV00CK7BRVbAOLZ4="
  [mod."github.com/census-instrumentation/opencensus-proto"]
    version = "v0.2.1"
    hash = "sha256-3RWTfGGuKbkrOQ91ociOgp9igGvU/FAv3NAidPVoYP8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/chzyer/logex"]
    version = "v1.1.10"
    hash = "sha256-BNOaV/CFAqOymWW3R2m1sCikdCwFZM/pVkylzoeU6yI="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/chzyer/test"]
    version = "v0.0.0-20180213035817-a1ea475d72b1"
    hash = "sha256-U0irpUSqegh7Nzg1ErPuyjESOcIXXOWf7ikKMbES2mY="
  [mod."github.com/client9/misspell"]
    version = "v0.3.4"
    hash = "sha256-MIKnt4va/nPl+5cCgOvCyRGIORTnguieQhlj8ery4BU="
  [mod."github.com/creack/pty"]
    version = "v1.1.9"
    hash = "sha256-Rj6c4/3IApJcS36iPVIEdlMSC/SWmywnpqk1500ik5k="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/docopt/docopt-go"]
    version = "v0.0.0-20180111231733-ee0de3bc6815"
    hash = "sha256-0mCKIC5x7aauBL8ahXB9ExMfoTJl55HaafWWWPNRmUI="
  [mod."github.com/elazarl/goproxy"]
    version = "v0.0.0-20180725130230-947c36da3153"
    hash = "sha256-aZb2tgdNc9f8k1wdT8+y71+AFJzgH4skELWhHwRVGaQ="
  [mod."github.com/emicklei/go-restful"]
    version = "v0.0.0-20170410110728-ff4f55a20633"
    hash = "sha256-LAhmOVQtqh1TKYhyzanQl/R24evmPr/2G38pQUKRtOw="
  [mod."github.com/envoyproxy/go-control-plane"]
    version = "v0.9.1-0.20191026205805-5f8ba28d4473"
    hash = "sha256-DFjKGsJUiBsD0+6E5zgyUDhjM2MWWqb3a7/0UueFuvg="
  [mod."github.com/envoyproxy/protoc-gen-validate"]
    version = "v0.1.0"
    hash = "sha256-2htufg3hdOHfbDVI5wFpsuaiDIhH6O1taUGJMdVbjlQ="
  [mod."github.com/evanphx/json-patch"]
    version = "v4.11.0+incompatible"
    hash = "sha256-GiV4D+OaD/onbgi51lmklA+ULGKOjm+R1Ej4Jnxp8Bc="
  [mod."github.com/form3tech-oss/jwt-go"]
    version = "v3.2.3+incompatible"
    hash = "sha256-2YU7EMWUrpWepYr0WXbiZjt7t4dhNeNq+e/IRQdNAG0="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/go-gl/glfw"]
    version = "v0.0.0-20190409004039-e6da0acd62b1"
    hash = "sha256-tqPStzM1xOuEWqAv4pBbzB+lNIxEqqyCCP0wWCbrlyY="
  [mod."github.com/go-gl/glfw/v3.3/glfw"]
    version = "v0.0.0-20200222043503-6f7a984d4dc4"
    hash = "sha256-6BfEsip1tEBelFTsKVtn2okCTb+0UsqEdIljg+PIjiE="
  [mod."github.com/go-logr/logr"]
    version = "v0.4.0"
    hash = "sha256-xeGTv0SMhCkLbIOH5Su2q/74B+OeOxsyEVYtQepF3/E="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.3"
    hash = "sha256-WZL/QvFB0OYyvHPNRhkl1BI0NT0TFMqRFlojX9hZi9Q="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.19.3"
    hash = "sha256-XDP7dJdwIl/AYU85bpKXX3twGJBlMhIrt96RE1UPwtI="
  [mod."github.com/go-openapi/swag"]
    version = "v0.19.5"
    hash = "sha256-D8qq6ZbWhLNroEisriI5d4zea5yQ7pzV/tl8XxjeZPw="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/glog"]
    version = "v0.0.0-20160126235308-23def4e6c14b"
    hash = "sha256-YDyL9TRikSXHSrYtITVA/ovYIYrdnZGym14XnslAYkk="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/mock"]
    version = "v1.4.1"
    hash = "sha256-5LaaCRbIvFrATowswmQRe+JRRcb4v7u67Qxf21YSw/E="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/btree"]
    version = "v1.0.1"
    hash = "sha256-1PIeFGgUL4BK/StL/D12pg9bEQ5HfMT/fMLdus4pZTs="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.5"
    hash = "sha256-pyfTIu1fx6cGYHhm+yi8YP2TgERnnqKRjqSV7WGb1Yk="
  [mod."github.com/google/gofuzz"]
    version = "v1.1.0"
    hash = "sha256-PSNufXo20YXfSNbayCc3hdujKZT5EW4lybsQ+WJ0Imo="
  [mod."github.com/google/martian"]
    version = "v2.1.0+incompatible"
    hash = "sha256-N3tPu89U5MQqmtFIqSEfqEXNgnHf883TAmXKvA2N8KQ="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20200229191704-1ebb73c60ed3"
    hash = "sha256-bogfN5hWzqf2kxEyA2XsUQu41nPcOBSvs1Z77x2zseI="
  [mod."github.com/google/renameio"]
    version = "v0.1.0"
    hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4="
  [mod."github.com/google/uuid"]
    version = "v1.1.2"
    hash = "sha256-DXttjObhEiMn5/OH+mYkJU6u03Gwsx5t08lTsIFyd+U="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.0.5"
    hash = "sha256-2ibpBbDxLVeYHd8gdszHb3w8rgKrChbUNlkaxW9lIhU="
  [mod."github.com/googleapis/gnostic"]
    version = "v0.5.5"
    hash = "sha256-KpSB2tHJsikuI86gZFCOod1MAbZEiiSrLCmVoAcm9X8="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/gregjones/httpcache"]
    version = "v0.0.0-20180305231024-9cad4c3443a7"
    hash = "sha256-2ngFfFuSm8YSTNZWGQuN5yTpsXlwY2R8aaIzjDnjTXI="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.1"
    hash = "sha256-/tr/EXgTmXPqrrx6kdMPMfWSC6GBdCPlX8GEuRk4yI0="
  [mod."github.com/hpcloud/tail"]
    version = "v1.0.0"
    hash = "sha256-7ByBr/RcOwIsGPCiCUpfNwUSvU18QAY+HMnCJr8uU1w="
  [mod."github.com/ianlancetaylor/demangle"]
    version = "v0.0.0-20181102032728-5e5cf60278f6"
    hash = "sha256-5cS82VAt2PtDlx18XzvNwhp7zk/fryC9HCzdyEKYEro="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.5"
    hash = "sha256-644gtN58Py6dYU8OAM10R95YuD2W4Aj3ZS+NuxOyb9c="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.11"
    hash = "sha256-/rcZZy458AsEqrSgtneGghVUpHNXJfT66QQHI6hyERU="
  [mod."github.com/jstemmer/go-junit-report"]
    version = "v0.9.1"
    hash = "sha256-fK6zLXQU8y+h+SqyeCUldA5OFPA/j0Wlbizk6AG60c4="
  [mod."github.com/kisielk/errcheck"]
    version = "v1.5.0"
    hash = "sha256-ZmocFXtg+Thdup+RqDYC/Td3+m1nS0FydZecfsWXIzI="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/kr/pretty"]
    version = "v0.2.0"
    hash = "sha256-127gkrb5HVPOCp0sGZOmiJPaQuQ4zptRw0MNGP53i/s="
  [mod."github.com/kr/pty"]
    version = "v1.1.1"
    hash = "sha256-AVeS+ivwNzIrgWQaLtsmO2f2MYGpxIVqdac/EzaYI1Q="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/mailru/easyjson"]
    version = "v0.0.0-20190626092158-b2ccc519800e"
    hash = "sha256-6tSxxb/n5O4/UYZRXHYYfi0WZBWX1gIiQclBC0oQlJI="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.1.2"
    hash = "sha256-OU9HZYHtl0qaqMFd84w7snkkRuRY6UMSsfCnL5HYdw0="
  [mod."github.com/moby/spdystream"]
    version = "v0.2.0"
    hash = "sha256-Feme5UoWuBCvnLPKw1ozKkF3SM7PAjjPFQZ3TJhghR0="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.1"
    hash = "sha256-5D1HGVBc/REwPVdlPYcXsbZM80OIh7V5uiyKAbMA5qo="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20120707110453-a547fc61f48d"
    hash = "sha256-ESdY/qfmo5a9Mwxccq3MMBde4DsoTdPO9WFj2IuFcKY="
  [mod."github.com/mxk/go-flowrate"]
    version = "v0.0.0-20140419014527-cca7078d478f"
    hash = "sha256-gRTfRfff/LRxC1SXXnQd2tV3UTcTx9qu90DJIVIaGn8="
  [mod."github.com/niemeyer/pretty"]
    version = "v0.0.0-20200227124842-a10e7caefd8e"
    hash = "sha256-m2D7hWZrDst0rb91lmjSuNrzBQbmQ0Oe2UOp3wn8qso="
  [mod."github.com/nxadm/tail"]
    version = "v1.4.4"
    hash = "sha256-S336Q+5j2uVmwLOfEUpU0iFBEEDH+UtdQO0NWPsc9OY="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.14.0"
    hash = "sha256-Vv2tuMhqoNc76LJkV79SUQWTtFoEXnHj11hW4gSTr0Y="
  [mod."github.com/onsi/gomega"]
    version = "v1.10.1"
    hash = "sha256-uIn5IR1oT3Q9eXbLsBlIbXJRYEIk401xSzZRvlqOFRk="
  [mod."github.com/peterbourgon/diskv"]
    version = "v2.0.1+incompatible"
    hash = "sha256-K4mEVjH0eyxyYHQRxdbmgJT0AJrfucUwGB2BplRRt9c="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.0.0-20190812154241-14fe0d1b01d4"
    hash = "sha256-oJSU4o77UVps0e2SJUDz6enypNipZPDdZmn0tbKZtX0="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.5.2"
    hash = "sha256-5LAHJam4xU7MvQxL91UL66Zx4UTLCE6hrtv5A+JCpw4="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.3.0"
    hash = "sha256-JgiasZeXDy10syy7wmXtqRffDY7CJ1o5VNY+FmmAjVU="
  [mod."github.com/spf13/afero"]
    version = "v1.2.2"
    hash = "sha256-SZVSWEvRzFGZm5u384Rp/LU0dyJ00oIqEQOV9nAxOUk="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.2.0"
    hash = "sha256-Vc8Ecx5DBeAK89TgqxaHV7TUrpjGMUdV6cOc3FM297A="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/tidwall/btree"]
    version = "v1.7.0"
    hash = "sha256-bnr6c7a0nqo2HyGqxHk0kEZCEsjLYkPbAVY9WzaZ30o="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/redcon"]
    version = "v1.6.2"
    hash = "sha256-EhMOHoYAucg7ahRc9ALiEOluvJCAVd9nwy7BKfDt6bc="
  [mod."github.com/yuin/goldmark"]
    version = "v1.2.1"
    hash = "sha256-vrL87IsRgYTTHvCH2fodVu+ECk9UCu4kuCy3Ypy2Oos="
  [mod."go.opencensus.io"]
    version = "v0.22.3"
    hash = "sha256-A6qNyBe3ubB3hu8VJKEzo4uohvhP3dI6hOwItlvxVW8="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210220033148-5ea612d1eb83"
    hash = "sha256-ZacGMV1CFBAmShBQ/dN+C8Ls5ECHXXZdUiI1hcu4cFU="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20200224162631-6cc2880d07d6"
    hash = "sha256-bhrVk10F9h0g3uRn+rJEA66KqUNy6fG2H56T04KfXPk="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20190802002840-cff245a6509b"
    hash = "sha256-BP2l1VUXd5afv4fsZ9g6WYy6zEPY782ZAsMrFSe1P0I="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20200302205851-738671d3881b"
    hash = "sha256-LNkJ9QCzsDgFjrLI+hYNISu9jrsu9tX9tFKm4i/5cUo="
  [mod."golang.org/x/mobile"]
    version = "v0.0.0-20190719004257-d2bd2a29d028"
    hash = "sha256-At0uE2mTr/GHCyF4U8Z+AiU2jlvBVQuX25tooo2ll6M="
  [mod."golang.org/x/mod"]
    version = "v0.6.0-dev.0.20220419223038-86c51ed26bb4"
    hash = "sha256-HS5GtzK6mLkQ/FM+GWoX4wSW0XllHK/2O3Y7O2/sFBk="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210520170846-37e1c6afe023"
    hash = "sha256-dwPXxrv+JephmrlF5fRdypRTd4ka/VFx7jbvJEzOXr0="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20200107190931-bf48bf16ab8d"
    hash = "sha256-r+VK6vgr8pMOmLXonG6YhBSUQ+kZJzdHgpV/YFZsOeo="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20201020160332-67f06af15bc9"
    hash = "sha256-hfvviA1/duBMtleic86KvYNlUz3/V7XKVAggZtUldyQ="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220722155257-8c9f86f7a55f"
    hash = "sha256-mXgFTb2vfUEjTPA6PX7CZTvKGJWaxoU2QplyI1GjC+w="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210220032956-6a3ed077a48d"
    hash = "sha256-BQ9U/OJuxKwVGsfMff6reDsBTmBiDSGmMy5lgYdF0XY="
  [mod."golang.org/x/text"]
    version = "v0.3.8"
    hash = "sha256-KKHU0OMfT4oxTIzIVqan8MY8wNvgBW00s24hF+kWbMA="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."golang.org/x/tools"]
    version = "v0.1.12"
    hash = "sha256-D0kGneGMt+LFbdUDo9Axd0yB0a5t3Z0YKVAnJDDaBo8="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/api"]
    version = "v0.20.0"
    hash = "sha256-m7nqVlRss1EJbNEn7uIOXxXdspqNtlcxpMQotWCgJm8="
  [mod."google.golang.org/appengine"]
    version = "v1.6.5"
    hash = "sha256-cE9jZUiPSk7GMhhpdcl4NS6OkGqwh9IU3exKiqs+3ns="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20201019141844-1ed22bb0c154"
    hash = "sha256-LjPOXSbb9owLJQmyoI8Zwys/zwu69kZuNUU6HxZW5v8="
  [mod."google.golang.org/grpc"]
    version = "v1.27.1"
    hash = "sha256-jPk1fgEH3hVbXuSCY2kGXdWZoRom+wkmnx82fyrxnB4="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20200227125254-8fa46927fb4f"
    hash = "sha256-nGV66SlDrpDfhkzlr9h52JybsCioW3ix5bKmbkEfoDs="
  [mod."gopkg.in/errgo.v2"]
    version = "v2.1.0"
    hash = "sha256-Ir/MuxQFxvVJEciovGOZbM8ZfKJ/AYotPwYfH2FctRg="
  [mod."gopkg.in/fsnotify.v1"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0"
    hash = "sha256-XWfvIV7+KXlZV4sBZd0srGeuQonS9cTYptCc6NcgVvc="
  [mod."honnef.co/go/tools"]
    version = "v0.0.1-2020.1.3"
    hash = "sha256-UI1MNNdyH+nfW7ShzHHTNNlmxOLeJVMSgf8ZfQtcEV8="
  [mod."k8s.io/api"]
    version = "v0.22.2"
    hash = "sha256-DXAn/q5GE86vcO3KOHk30Ve9f6DDl5ooHWTG1kll3Yk="
  [mod."k8s.io/apimachinery"]
    version = "v0.22.2"
    hash = "sha256-TUg+uQWYw/k9GtBoFoparT9+GReG/zY1HvDgReAH/4w="
  [mod."k8s.io/client-go"]
    version = "v0.22.2"
    hash = "sha256-DAmH1NENDtLkxBsipHS5xEm8uagCkGrjoGr5tGGC8hk="
  [mod."k8s.io/gengo"]
    version = "v0.0.0-20200413195148-3a45101e95ac"
    hash = "sha256-QSlK7SjCMtlY2OuJCFYQXzZqvLotsMWF0D29yyciGyg="
  [mod."k8s.io/klog/v2"]
    version = "v2.9.0"
    hash = "sha256-k8Zj7Ypn6UJRyprmWD3bvgoAXQI1CmPIjqugsdRBYFk="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20210421082810-95288971da7e"
    hash = "sha256-Jua9Coid7u8Zqzvzas7u4eVp5KIHwYGWw8Q7ZqEec9s="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20210819203725-bdf08cb9a70a"
    hash = "sha256-twbsCnkBI6tf0oRp2K7mfBAkom0QFUmynwnoa5ggFfk="
  [mod."rsc.io/binaryregexp"]
    version = "v0.2.0"
    hash = "sha256-izALTmzybQe67BNXliqQ3xCEOo+b6o8C4YoX5H0FWc0="
  [mod."rsc.io/quote/v3"]
    version = "v3.1.0"
    hash = "sha256-sF7lOq/bInDPtLI+j610WJRAQ09Cxc5lmPzzytuE6DI="
  [mod."rsc.io/sampler"]
    version = "v1.3.0"
    hash = "sha256-UPbUO3GOGn6/fz1EBEYONBX45V6bzQKQv6CoZb2Y3S8="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.1.2"
    hash = "sha256-3K0/Dl649UR/f067hi7kOoXdiTHJuWlMZKeNOvJFA2k="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.2.0"
    hash = "sha256-HHqIfaFuKGalif3bP2CcHm8MT8Ily1kJQL9Q8Kz2WHA="
