// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	. "github.com/kurtosis-tech/kardinal/libs/cli-kontrol-api/api/golang/types"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /deploy)
	PostDeploy(ctx echo.Context) error

	// (POST /flow/create)
	PostFlowCreate(ctx echo.Context) error

	// (POST /flow/delete)
	PostFlowDelete(ctx echo.Context) error

	// (GET /topology)
	GetTopology(ctx echo.Context, params GetTopologyParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostDeploy converts echo context to params.
func (w *ServerInterfaceWrapper) PostDeploy(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDeploy(ctx)
	return err
}

// PostFlowCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostFlowCreate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFlowCreate(ctx)
	return err
}

// PostFlowDelete converts echo context to params.
func (w *ServerInterfaceWrapper) PostFlowDelete(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFlowDelete(ctx)
	return err
}

// GetTopology converts echo context to params.
func (w *ServerInterfaceWrapper) GetTopology(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTopologyParams
	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", ctx.QueryParams(), &params.Namespace)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTopology(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/deploy", wrapper.PostDeploy)
	router.POST(baseURL+"/flow/create", wrapper.PostFlowCreate)
	router.POST(baseURL+"/flow/delete", wrapper.PostFlowDelete)
	router.GET(baseURL+"/topology", wrapper.GetTopology)

}

type PostDeployRequestObject struct {
	Body *PostDeployJSONRequestBody
}

type PostDeployResponseObject interface {
	VisitPostDeployResponse(w http.ResponseWriter) error
}

type PostDeploy200JSONResponse string

func (response PostDeploy200JSONResponse) VisitPostDeployResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostFlowCreateRequestObject struct {
	Body *PostFlowCreateJSONRequestBody
}

type PostFlowCreateResponseObject interface {
	VisitPostFlowCreateResponse(w http.ResponseWriter) error
}

type PostFlowCreate200JSONResponse string

func (response PostFlowCreate200JSONResponse) VisitPostFlowCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostFlowDeleteRequestObject struct {
	Body *PostFlowDeleteJSONRequestBody
}

type PostFlowDeleteResponseObject interface {
	VisitPostFlowDeleteResponse(w http.ResponseWriter) error
}

type PostFlowDelete200JSONResponse string

func (response PostFlowDelete200JSONResponse) VisitPostFlowDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTopologyRequestObject struct {
	Params GetTopologyParams
}

type GetTopologyResponseObject interface {
	VisitGetTopologyResponse(w http.ResponseWriter) error
}

type GetTopology200JSONResponse Topology

func (response GetTopology200JSONResponse) VisitGetTopologyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /deploy)
	PostDeploy(ctx context.Context, request PostDeployRequestObject) (PostDeployResponseObject, error)

	// (POST /flow/create)
	PostFlowCreate(ctx context.Context, request PostFlowCreateRequestObject) (PostFlowCreateResponseObject, error)

	// (POST /flow/delete)
	PostFlowDelete(ctx context.Context, request PostFlowDeleteRequestObject) (PostFlowDeleteResponseObject, error)

	// (GET /topology)
	GetTopology(ctx context.Context, request GetTopologyRequestObject) (GetTopologyResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostDeploy operation middleware
func (sh *strictHandler) PostDeploy(ctx echo.Context) error {
	var request PostDeployRequestObject

	var body PostDeployJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostDeploy(ctx.Request().Context(), request.(PostDeployRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDeploy")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostDeployResponseObject); ok {
		return validResponse.VisitPostDeployResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostFlowCreate operation middleware
func (sh *strictHandler) PostFlowCreate(ctx echo.Context) error {
	var request PostFlowCreateRequestObject

	var body PostFlowCreateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostFlowCreate(ctx.Request().Context(), request.(PostFlowCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFlowCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostFlowCreateResponseObject); ok {
		return validResponse.VisitPostFlowCreateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostFlowDelete operation middleware
func (sh *strictHandler) PostFlowDelete(ctx echo.Context) error {
	var request PostFlowDeleteRequestObject

	var body PostFlowDeleteJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostFlowDelete(ctx.Request().Context(), request.(PostFlowDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFlowDelete")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostFlowDeleteResponseObject); ok {
		return validResponse.VisitPostFlowDeleteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTopology operation middleware
func (sh *strictHandler) GetTopology(ctx echo.Context, params GetTopologyParams) error {
	var request GetTopologyRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTopology(ctx.Request().Context(), request.(GetTopologyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTopology")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTopologyResponseObject); ok {
		return validResponse.VisitGetTopologyResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RVTU/jSBD9K63aPexKdhzg5tsuaBFihZBAc0Fo1LQrdoPd1XRXAhHKfx91t+MQYoX5",
	"0GiYm+2qV/Xeq1L5BRR1lgwa9lC+gFcNdjI+nuDiv5aeriyq8GodWXSsMQYrUg/o8gj2GL5oxi6GnvOa",
	"cl5ahBL6+OQK3UIrPCYz0zVkm5xcd5YcB5yR3SsIZGAlN1BCrbmZ300UdUUfy71FNbzUVIRKHlarDPq+",
	"0jm5hFUGupM15i0pyeRCF3yWnW1Dzp1UD2iqXJatZPQMA9qz06YOcJ9454nbGHqdIXfhGzp0d4+KQ8FT",
	"J22za6ehKj0MLv7pcAYl/FFs5lP0wykuqELYETvWLmbudNPVtpbQPT/Yo//ie+QP6E/ovCazXeBgMp1M",
	"x0As2wf/mWkr/SZxPIQsPRzBbbbxarfGu8ZcOqp+9+0e03VNllqql7ua6vXm7dustJ4jlcMnbWZxKqw5",
	"jvD4/7PivKV5lZ+TYUet+OfyDDJYrOfdD3mVAVk00moo4aife5AfeRUV2pYSYfLRq0BbsiZzVkEJl+T5",
	"JOVk4PBxjp7/pSoiFBlGE0HS2larCCvufVq3JOs90Vu7EJVW6JXTlpOK1FxIYR1Vgky7FKqde0bXE9IO",
	"KyjZzXEVPnhLxifTD6fTb6L59oKMcFmIWUtPQjmMRYRnyfOwHiG5CLEixnC/o0Hwccr7Oa6+/n2MCEm9",
	"hRRVr+iDellhi1/j5UnK+1UbGpoPVoq/HC7QsQhXWjBtFvfvj+cyv7pYNY44fIo8XLVwN5zskNF5KG9e",
	"3vS6blCEQ+utVChm5MRTo1UTLHDITuMCBTcoeFNPB9zjHF146Y/0UAKyPUpvf9C5fQMfBI8Yuo6JcI9d",
	"F8tHM1erLwEAAP//xCZwK84JAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
