apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-voting-api
  labels:
    app: docs-voting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-voting-api
  template:
    metadata:
      labels:
        app: docs-voting-api
    spec:
      containers:
        - name: docs-voting-api
          image: tedim52/docs-voting-app:latest
          ports:
            - containerPort: 9111
          env:
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: docs-voting-api
spec:
  selector:
    app: docs-voting-api
  ports:
    - protocol: TCP
      port: 9111
      targetPort: 9111
  type: LoadBalancer