// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	. "github.com/kurtosis-tech/kardinal/libs/manager-kontrol-api/api/golang/types"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Cluster resource definition
	// (GET /cluster-resources/{identifier})
	GetClusterResourcesIdentifier(ctx echo.Context, identifier Identifier) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClusterResourcesIdentifier converts echo context to params.
func (w *ServerInterfaceWrapper) GetClusterResourcesIdentifier(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "identifier" -------------
	var identifier Identifier

	err = runtime.BindStyledParameterWithOptions("simple", "identifier", ctx.Param("identifier"), &identifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter identifier: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClusterResourcesIdentifier(ctx, identifier)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/cluster-resources/:identifier", wrapper.GetClusterResourcesIdentifier)

}

type NotOkJSONResponse ResponseInfo

type GetClusterResourcesIdentifierRequestObject struct {
	Identifier Identifier `json:"identifier"`
}

type GetClusterResourcesIdentifierResponseObject interface {
	VisitGetClusterResourcesIdentifierResponse(w http.ResponseWriter) error
}

type GetClusterResourcesIdentifier200JSONResponse ClusterResource

func (response GetClusterResourcesIdentifier200JSONResponse) VisitGetClusterResourcesIdentifierResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClusterResourcesIdentifierdefaultJSONResponse struct {
	Body       ResponseInfo
	StatusCode int
}

func (response GetClusterResourcesIdentifierdefaultJSONResponse) VisitGetClusterResourcesIdentifierResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Cluster resource definition
	// (GET /cluster-resources/{identifier})
	GetClusterResourcesIdentifier(ctx context.Context, request GetClusterResourcesIdentifierRequestObject) (GetClusterResourcesIdentifierResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetClusterResourcesIdentifier operation middleware
func (sh *strictHandler) GetClusterResourcesIdentifier(ctx echo.Context, identifier Identifier) error {
	var request GetClusterResourcesIdentifierRequestObject

	request.Identifier = identifier

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetClusterResourcesIdentifier(ctx.Request().Context(), request.(GetClusterResourcesIdentifierRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClusterResourcesIdentifier")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetClusterResourcesIdentifierResponseObject); ok {
		return validResponse.VisitGetClusterResourcesIdentifierResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xZz27bOBN/lYDftzclTlvsxbei6RZG0TRw2u6hKASaGttsKZJLjtwYgd99QVKyJIuy",
	"JW/rmy0O5x/nNzPkPBOmcq0kSLRk+kw0NTQHBOP/8Qwk8iUH4/5lYJnhGrmSZEpwDVcGrCoMg6vZHUkI",
	"d581xTVJiKQ5kGmTQUIM/FNwAxmZoikgIZatIaeOM261o7ZouFyR3W7niK1W0oLX417hxx/uB1MSQaL7",
	"SbUWnFGnzeS7dSo9Nzj+38CSTMn/JrV5k7BqJ/OS9UwuVRDWtuyzhCcNDCG7AmOUIY6k3Ox4vxGFRTDz",
	"0njvNqM0GORB3Qy0UNu88ilHyO0ppe72e8guqRxCjaFbEhRELr2xqSkEjOG73zkvBMSYryjCT7o9xeld",
	"SeacAWbD2QgtHsOGmPQNN1hQkY7m+SVs7GVdf1CL78C8X98oiZTLEM/tQwO5GSz6rdx8oSZmDc/pCiIh",
	"Xa6kuhAi1Upwto1SBdxEFrQyI6Jpb+eDMtGAqpBrG8IqNx11nGfYcR6rllNdrpccuERYgTlumlGomBKx",
	"TBBRpYGUjh5U83QDxvKQD+CJ5lq47ZsXJOlK/sFl1qZrMI/Q54A0o3gyw3yo6BxWNLDh4H901G4XUiyG",
	"Hs7B9o5XDPhUaePnYkEAQxWBRE6RrVNBFyCCd7OMu0RCxUOLruOnvT99mnZxp/W1P/+u+jGDLBqKsNqO",
	"8Fu1w7GDXAuKcGr3g8o+laTB7Sd821DqwL9KCC5XaaGzAWLngfqzJ27p7WUPxEA7qw8HggT8qcwPLlc3",
	"3CJXN1xNNi+o0Gv6aihE2rIvipOW6DPB0uXRcd9aWYxGti0WFkYk4kdPP6w4lVXlTKCVHdf87d3skSRk",
	"Q0Xh/hvIuL3WRmUkJvNdXfsvFkCVzAsGTinyrIBp7u24qT95eucMhLPrfaqWe2g7BWZYVH1wSfyu9Glb",
	"xb5a3ctmrgqEnjoxWPlaoVhfUkkYxMrr0wD0QI80guwg6KVU6DmdXe8sz4BRU2ODSy/X33li2jADoa9H",
	"nkNqkeba8Vkqk1MkU+KqxLVbi+HlN9fmI02bW7CasqEV60FlcQTtW8czutth531Y57vx+5uyTmVzj1ax",
	"Rvpo/x/v3460zwlBalaADyOA3rodR04rg1Z4Flziq5d1bDYUy8HavttQ1esMuad/crThTaB6QPgaGNQy",
	"kqDZtyMGfSpFgixyx+HtfP5xThIyu//rI0nI36/n97P7dw0Wtbbxli2SB59SW5hgcl3vXv75R7TW0ae0",
	"kHRDuaALMWRP9LgOU2DkNeLI4olGZyC4fwJfrQdHWFm9orq0k0BP2NTlokLF6WIZLsL96oyEoyzyRbBh",
	"FCD75HMGv+EyW3G+YKNViuw2WkM2BeJjTorn73FvI31PIs1W7mI33bbpHcuEolm6oIJK1oq2oyz3yD3g",
	"9Z96hX0gkt67RA9YYqQHb3eXvH0ciL4gNtqSz7qLRFh0fFc+547MpGck3zWiHtf1h/tDhBWyX8MpArpd",
	"QnjZyiBHHwIfqKQrMJP3QhXZ9Xsl0Shx9fph5u7N+zh/cXN7c+tEKA2Sak6m5JX/lPghh9dzwsIs4Hr/",
	"njp5rmceO38cAYvuhHwNnmXuCgx4MEWws+aopDmG+Rp3R00yaUxZdt8ORicvb29/2eDkcPARmZ08FoyB",
	"tctCXFVqhPnFkhait1TvNZ6ESY8fuBR5Ts2WTKt5Sz1tymDJpc9gDr505ZxEOidBvu12u92/AQAA///+",
	"evOD4RoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
