# Our desired pipeline using only a Nix shell environment
name: Check and build Kardinal

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  check_nix:
    name: Check Nix
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v7
        with:
          fail-mode: true

      - name: Nix Check
        run: |
          nix flake check

  check_go:
    name: Check Go
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Check Go formatting
        run: |
          nix develop --command test -z $(gofmt -l .)

  build:
    name: Build
    needs: [check_nix, check_go]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        component: [kontrol-service, kontrol-frontend]
        # Skipping arm64 builds due GH cache rate limit casue by the
        # number of cache entries generated by pkgsCross builds
        arch: [amd64]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install qemu
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          # relax sandbox due impure kontrol-service tests during build
          extra_nix_config: |
            extra-platforms = aarch64-linux
            sandbox = relaxed

      - name: Magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Build ${{ matrix.component }}
        run: |
          nix build .#${{ matrix.component }} --no-link --print-out-paths

      - name: Build ${{ matrix.component }} for ${{ matrix.arch }}
        run: |
          nix build ./#containers.x86_64-linux.${{ matrix.component }}.${{ matrix.arch }} --no-link --print-out-paths
